name = "Argus"
uuid = "e39743ec-b2cc-45ef-a990-b666fc093538"
version = "0.1.0"
authors = ["Iulia Dumitru <iuliadmtru@gmail.com>"]

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
InteractiveUtils = "1.11.0"
JuliaSyntax = "1.0.0"
MacroTools = "0.5.15"
Test = "1.11.0"
